nodeLinker: node-modules

packageExtensions:
  "eslint-config-react-app@*":
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "ts-command-line-args@*":
    peerDependencies:
      "typescript": "*"
  "react-scripts@*":
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
